### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/screenshots#12]
@mar1u5 and @jospoortvliet  I just pushed and committed to master directly by accident. So I think the master should be a protected branch, enforcing PRs like we do in the source code repositories.

**Comment by MorrisJobke** [comment]
It is already protected, but you still can do normal pushes. Only force pushes are not allowed. Beside that we could enable LGTM bot here too and add this as status check before a PR is allowed to be merged.

**Comment by AndyScherzinger** [comment]
That would certainly be a solution I think.

**Comment by MorrisJobke** [comment]
Should work now. Please test it :)
