### ISSUE TITLE
New android screenshots 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/screenshots#36]
Hi,
I created with fastlane screenshots for 44 languages and three devices (phone, tablet 7" and tablet 10").
Shall I upload all of them into this repo? This would be ~370 Mb.
Or only upload english?

**Comment by jospoortvliet** [comment]
370 MB would make this repo a bit unwieldy... Stick to the english.

Alternatively, we could cull it to English/German/Spanish/French (maybe one more, Chinese?) and run the through https://tinypng.com before uploading - that will shave of at least half.

**Comment by tobiasKaminsky** [comment]
I'll use tinypng and upload only en-US 👍
