### ISSUE TITLE
The example server address is misleading

### ISSUE THREAD

**Issue by mabkenar** [nextcloud/screenshots#8]
In the login.png, it says above the text box: 
"Server address https://..."
And the example text is:
"nextcloud.com"

I don't think nextcloud.com domain is itself a Nextcloud provider, is it? If it isn't, then this screenshot may confuse users. They would probably complain that "I entered exactly the server address that was shown on the screenshot, but it didn't work."

I suggest we either leave it empty as before, or fill it with "https://MyNextCloudProvider.com" or something similar.

**Comment by MorrisJobke** [comment]
Fix in https://github.com/nextcloud/screenshots/pull/9
